pipeline {
    agent any
    stages{
        stage('Test App'){
            steps {
               sh 'cd setlist-app && python3 -m venv venv && source venv/bin/activate && pip3 install -r requirements.txt && python3 -m pytest --cov-report term-missing --cov=application tests/' 
            }
        }
        stage('Placeholder'){
            steps {
                sh 'ls'
            }
        }
        stage('Placeholder1'){
            steps {
                sh 'ls'
            }
        }
    }
}