pipeline {
    agent any
    stages{
        stage('Test App'){
            steps {
               sh 'cd setlist-app && python3 -m venv venv && ls && . ./venv/bin/activate && pip3 install -r requirements.txt && python3 -m pytest' 
            }
        }
        stage('Placeholder'){
            steps {
                sh 'ls'
            }
        }
        stage('Placeholder1'){
            steps {
                sh 'ls'
            }
        }
    }
}